export interface ICountry {
  name: {
    common: string,
    official: string,
    nativeName: Record<string, { official: string, common: string }>,
  },
  flag: string,
  tld?: string[],
  cca2?: string,
  ccn3?: string,
  cca3?: string,
  cioc?: string,
  independent?: boolean,
  status?: string,
  unMember?: boolean,
  currencies?: Record<string, { name: string, symbol: string }>,
  idd?: {
    root: string,
    suffixes: string[],
  },
  capital?: string,
  altSpellings?: string[],
  region?: string,
  subregion?: string,
  languages?: Record<string, string>,
  translations?: Record<string, { official: string, common: string }>,
  latlng?: number[],
  landlocked?: boolean,
  borders?: string[],
  area?: number,
  demonyms?: {
    eng: {
      f: string,
      m: string,
    },
    fra: {
      f: string,
      m: string,
    },
  },
  maps?: {
    googleMaps: string,
    openStreetMaps: string,
  },
  population?: number,
  gini?: number,
  timezones?: string[],
  continents?: string[],
  flags?: string[],
  coatOfArms?: string,
  startOfWeek?: string,
  capitalInfo?: string,
  postalCode?: {
    format: string,
    regex: string,
  },
  callingCode?: string[],
  politicalStatus?: string,
}
